await page.goto('http://localhost:5173/');
await page.getByRole('button', { name: 'Start Application' }).click();
await expect(page.getByRole('button', { name: 'Send OTP' })).toBeVisible();
await page.getByText('Phone Number', { exact: true }).click();
await page.getByRole('textbox', { name: 'Phone Number' }).click();
await page.getByRole('textbox', { name: 'Phone Number' }).fill('0712273948939');
await page.getByRole('button', { name: 'Send OTP' }).click();
await page.getByRole('textbox', { name: 'One-Time Password' }).click();
await page.getByRole('textbox', { name: 'One-Time Password' }).fill('0000');
await page.getByText('Enter the OTP sent to').click();
await page.getByRole('heading', { name: 'Verify OTP' }).click();
await page.getByRole('textbox', { name: 'One-Time Password' }).click();
await page.getByRole('button', { name: 'Verify' }).click();
await page.getByRole('textbox', { name: 'Full Name *' }).click();
await page.getByRole('textbox', { name: 'Full Name *' }).fill('is ');
await page.getByRole('textbox', { name: 'Full Name *' }).press('CapsLock');
await page.getByRole('textbox', { name: 'Full Name *' }).fill('isJS ');
await page.getByRole('textbox', { name: 'National ID *' }).click();
await page.getByRole('textbox', { name: 'National ID *' }).fill('23837736');
await page.getByRole('textbox', { name: 'Email Address' }).click();
await page.getByRole('textbox', { name: 'Email Address' }).fill('sk@gsi.com');
await page.getByRole('textbox', { name: 'Date of Birth *' }).fill('1221-02-12');
await expect(page.getByRole('textbox', { name: 'Full Name *' })).toBeVisible();
await page.getByRole('textbox', { name: 'National ID *' }).click();
await page.getByRole('textbox', { name: 'Email Address' }).click();
await page.getByRole('textbox', { name: 'Email Address' }).dblclick();
await page.getByRole('textbox', { name: 'Email Address' }).click();
await page.getByText('Date of Birth *').click();
await page.getByText('Email Address').click();
await page.getByText('National ID *').click();
await page.getByText('Full Name *').click();
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('spinbutton', { name: 'Loan Amount *' }).click();
await page.getByRole('spinbutton', { name: 'Loan Amount *' }).fill('999');
await page.getByLabel('Loan Term (days) *').selectOption('30');
await page.getByRole('textbox', { name: 'Purpose *' }).click();
await page.getByRole('textbox', { name: 'Purpose *' }).fill('builds');
await page.getByText('Loan Amount *').click();
await page.getByText('Loan Term (days) *').click();
await page.getByText('Purpose *').click();
await page.getByRole('button', { name: 'Submit Application' }).click();
await page.getByText('Loan amount must be at least').click();
await page.getByText('Loan amount must be at least').click();
await page.getByRole('spinbutton', { name: 'Loan Amount *' }).click();
await page.getByRole('spinbutton', { name: 'Loan Amount *' }).fill('292929292');
await page.getByText('Loan amount must be at least').click();
await page.getByRole('button', { name: 'Submit Application' }).click();
await page.getByText('Loan amount cannot exceed').click();
await page.getByRole('spinbutton', { name: 'Loan Amount *' }).click();
await page.getByRole('spinbutton', { name: 'Loan Amount *' }).click();
await page.getByRole('spinbutton', { name: 'Loan Amount *' }).fill('5000000');
await page.getByRole('button', { name: 'Submit Application' }).click();
await page.getByText('PENDING').click();
await page.getByText('⏳ Your application is under').click();
await page.getByText('Submitted:').click();
await page.getByText('/01/2026, 10:36:46').click();
await page.getByText('Loan Term:').click();
await page.getByText('days').click();
await page.getByText('UGX').click();
await page.getByText('Loan Amount:').click();
await page.getByText('Applicant:').click();
await page.getByRole('button', { name: 'Logout' }).click();